// <auto-generated />
namespace GIBDD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class numb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(numb));
        
        string IMigrationMetadata.Id
        {
            get { return "202011231505143_numb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
